--Consulta nueva para generar listado de boletas por rango de fechas incluyendo los timbres fiscales

SELECT DC.FECHA, DC.ING_COD AS CODIGO_INGRESO, FP.ING_DSC AS DESCRIPCION, 
DC.NO_DOCU AS BOLETA, CA.NBR_COBRADOR AS CONTRIBUYENTE, CA.CONCEPTO, DC.MONTO 
FROM ARCCDC DC, ARCCCA CA, FP_ING FP  
WHERE DC.TIPO =  'C' AND DC.NO_DOCU = CA.NO_DOCU AND DC.FECHA BETWEEN 
to_date('20230101', 'YYYYMMDD') AND to_date('20231231', 'YYYYMMDD') AND 
DC.ING_COD = FP.ING_COD
UNION
SELECT DC.FECHA, DC.ING_COD AS CODIGO_INGRESO, 'Timbre Fiscal' AS DESCRIPCION , 
DC.NO_DOCU AS BOLETA, CA.NBR_COBRADOR AS CONTRIBUYENTE, CA.CONCEPTO, DC.MONTO 
FROM ARCCDC DC, ARCCCA CA  
WHERE DC.TIPO =  'C' AND DC.NO_DOCU = CA.NO_DOCU AND DC.FECHA BETWEEN 
to_date('20230101', 'YYYYMMDD') AND to_date('20231231', 'YYYYMMDD') AND 
DC.ING_COD = 'S.E.P';



